.github/workflows/ci_publish.yml
conf.py
tutorials/requirements.txt

This is to debug the circleCI redirect workflow for PRs as the config below should not run on PRs

CI: adding HTML publishing workflow

---

.circleci/config.yml
.github/workflows/ci_tests_run_notebooks.yml
conf.py
ignore_osx_testing
ignore_testing
ignore_windows_testing
tox.ini
tutorials/parallelize/Parallelize_Convolution.md
tutorials/requirements.txt

For some reason, this doesn't work locally, so I hope it maybe an osx issue and things are still ok at least on linux

Enable testing for the parallel notebook

---

.github/workflows/ci_tests_run_notebooks.yml

CI: fix 'html rendering' test skip logic

---

.github/dependabot.yml

CI: adding monthly dependabot

---

conf.py
ignore_gha_testing
index.md
tox.ini
tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
tutorials/parquet-catalog-demos/neowise-source-table-strategies.md
tutorials/requirements.txt

Adds two notebooks that demo access to the parquet version of NEOWISE Single-exposure Source Table:
- neowise-source-table-strategies.md
- neowise-source-table-lightcurves.md

Add notebooks for NEOWISE parquet catalog

---

index.md
tutorials/cloud_access/cloud-access-intro.md
tutorials/cosmodc2/cosmoDC2_TAP_access.md
tutorials/firefly/NEOWISE_light_curve_demo.md
tutorials/firefly/SEDs_in_Firefly.md
tutorials/irsa-sia-examples/sia_2mass_allsky.md
tutorials/irsa-sia-examples/sia_allwise_atlas.md
tutorials/irsa-sia-examples/sia_cosmos.md
tutorials/irsa-sia-examples/siav2_seip.md
tutorials/openuniversesims/openuniverse2024_roman_simulated_timedomainsurvey.md
tutorials/openuniversesims/openuniverse2024_roman_simulated_wideareasurvey.md
tutorials/parallelize/Parallelize_Convolution.md
tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
tutorials/parquet-catalog-demos/neowise-source-table-strategies.md
tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md

This should tick the remaining boxes for https://github.com/Caltech-IPAC/irsa-tutorials/issues/12

DOC: cleanup about sections

---

.binder/requirements.txt
index.md
tox.ini
tutorials/firefly/NEOWISE_light_curve_demo.md
tutorials/firefly/OpenUniverse2024Preview_Firefly.md
tutorials/firefly/SEDs_in_Firefly.md

- Adds OpenUniverse notebook
- Updates in other 2 firefly notebooks
- Homogenize how to instantiate firefly-client
- API update in SEDs notebook
- More descriptive headings in NEOWISE notebook
- Adds FIREFLY_URL to env (just in case) as fallback

Add OpenUniverse2024 Firefly notebook and update other firefly notebooks

---

tutorials/firefly/OpenUniverse2024Preview_Firefly.md

Follow-up for addressing review comments on #40 
- Added a pip install cell
- Converted links in the text to hyperlinks for better rendering

Improve OpenUniverse2024 Firefly notebook

---

tutorials/cosmodc2/cosmoDC2_TAP_access.md

My expectation for this to fix the frequent timeouts.
TODO: change the narrative docs to add a sentence or two about sync and async. I'll do that once this cleans CI.
Close #43

ENH: switching to use async TAP cosmodc2

---

tutorials/parquet-catalog-demos/neowise-source-table-lightcurves.md
tutorials/parquet-catalog-demos/neowise-source-table-strategies.md

This PR is on hold until the files are available in S3. -- Update 2025-03-08: Ready to go.

IRSA-6436 Add NEOWISE year11 and addendum

---

.binder/requirements.txt
tutorials/cloud_access/euclid-cloud-access.md
tutorials/euclid_access/Euclid_ERO.md

This only adds the changes to the notebooks already using astroquery but we'll rely on similar 0.4.10 features in the ones where I'm swapping out pyvo with astroquery.
This PR one is ready to go.

Updating tutorials with new astroquery features

---

ignore_gha_testing
tutorials/euclid_access/Euclid_ERO.md

Most of the notebooks can be added to the CI. For now I leave out the two that runs into troubles with resources at rendering.

CI: Adding notebooks to the CI

---

tox.ini
tutorials/euclid_access/3_Euclid_intro_1D_spectra.md

We should not hit the servers unnecessarily
(included some code changes here, too, so we eventually have some test diffs in this PR, but all those need to be reverted before merging)

CI: test only diffed notebooks

---

index.md
tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md

This notebook could use some more narrative text, so we are not shipping it out just yet

Adding Euclid notebook4

---

tutorials/euclid_access/1_Euclid_intro_MER_images.md
tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md

Removed the MER download and plot, and renamed the spe lines table from table_spe to table_lines for clarity, as there are multiple spe tables

Euclid notebooks: refactor the MER download and plot parts

---

tutorials/cloud_access/euclid-cloud-access.md
tutorials/euclid_access/1_Euclid_intro_MER_images.md
tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md

DOC: updating Euclid intros and titles

---

tutorials/cloud_access/cloud-access-intro.md
tutorials/cloud_access/euclid-cloud-access.md
tutorials/euclid_access/1_Euclid_intro_MER_images.md
tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md
tutorials/euclid_access/Euclid_ERO.md
tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md

I also added a note about this to the template docs.
Closes #65

MAINT: fix pip install lines

---

conf.py
ignore_gha_testing
tox.ini

These should not hit the limit any more.
Fixes #88

CI: add back euclid tutorials to testing

---

tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md

This PR cleans up the code a bit to use more astropy features, e.g. enable WCS aware matplotlib plotting thus eliminating the need for some manual conversions.
It also cleans up the pandas usage, I haven't identified anything that was dataframe specific, so we can totally rely on Table/QTable features.
I have also added some tips and warnings around the astropy usage, but feel that all of these notebooks could still use some added narrative around Euclid itself.

MAINT: cleanup euclid4 and introduced a couple of astropy features

---

README.md

DOC: adding myst markdown to the readme

---

tox.ini

This is a temporary workaround until https://github.com/jupyter-book/mystmd/issues/2113 is resolved upstream

CI: making sure we fail buildhtml job with tracebacks
