Caltech-IPAC/irsa-tutorials

.circleci/config.yml, tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md
Somehow this notebook causes a kernel error in circleCI. I cannot reproduce it locally, nor GHA has problems. 
Either way, some workaround will need to be in place so we have a passing build status for the other notebooks.
=> Workaround for circleCI DeadKernelError

tutorials/cloud_access/cloud-access-intro.md
- Make the installs a simple one liner. Remove the try/except block. (prompted by https://github.com/IPAC-SW/ipac-sp-notebooks/issues/39)
- Wrap long code lines.
=> Simplify the install cell (cloud-access-intro.md)

.github/workflows/ci_publish.yml, .github/workflows/ci_tests_run_notebooks.yml
The is no need to run the test matrix for PRs like #25 
I would even go as far as there is no need to execute the notebooks for such PRs in circleCI, however it sounds a bit hacky and ugly how such a workaround can be added there (as I see there isn't an easy way to get access to the github labels to write such a conditional there just outstanding feature requests such as https://ideas.circleci.com/cloud-feature-requests/p/provide-github-labels-for-filtering, and even then we need to sed nb_execution_mode to be off in the tox config before it is being picked up by the runner...)
=> ENH: adding conditional to test execution

.github/workflows/ci_tests_run_notebooks.yml, index.md, tox.ini, tutorials/cloud_access/cloud-access-intro.md, tutorials/cosmodc2/cosmoDC2_TAP_access.md, tutorials/firefly/NEOWISE_light_curve_demo.md, tutorials/firefly/SEDs_in_Firefly.md, tutorials/irsa-sia-examples/sia_2mass_allsky.md, tutorials/irsa-sia-examples/sia_allwise_atlas.md, tutorials/irsa-sia-examples/sia_cosmos.md, tutorials/irsa-sia-examples/siav2_seip.md, tutorials/openuniversesims/openuniverse2024_roman_simulated_timedomainsurvey.md, tutorials/openuniversesims/openuniverse2024_roman_simulated_wideareasurvey.md, tutorials/parallelize/Parallelize_Convolution.md, tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md
This also adds top level headings as captions to the sidebar. Downside of this workaround is that those are not linked to the achors, so it's not possible to use them to navigate back. It also won't work once we add one more layer of headings in the index page (like it was in the first draft, before this PR)
I saw some other workarounds, so can keep experimenting if we
=> HTML: restructure index page headings

.github/workflows/ci_tests_run_notebooks.yml, ignore_osx_testing, tutorials/requirements.txt
This is to test the fix from https://github.com/Caltech-IPAC/firefly_client/pull/61
More context: https://github.com/Caltech-IPAC/irsa-tutorials/pull/10#issuecomment-2263766740 and below
cc @jaladh-singhal
=> CI: enable firefly osx

conf.py, tox.ini
Rendering job should now fail on tracebacks. Also added OSX and Windows rendering exception
=> CI: fail rendering job on errors

conf.py
This would make some of the tutorial renderings nicer, e.g. the openuniverse timeseries (but I see it improved a few others, too): 
vs
=> ENH: merge streams for nicer looking outputs

.github/workflows/ci_tests_run_notebooks.yml
The need for this came up in https://github.com/Caltech-IPAC/irsa-tutorials/pull/16 where the newly added content runs out of circleCI resources, but it's not clear whether it would do the same on GHA (as other notebooks execute without issues on GHA but not on circleCI)
=> CI: add optin to build html on GHA

tutorials/cloud_access/cloud-access-intro.md, tutorials/cosmodc2/cosmoDC2_TAP_access.md, tutorials/firefly/NEOWISE_light_curve_demo.md, tutorials/firefly/SEDs_in_Firefly.md, tutorials/irsa-sia-examples/sia_2mass_allsky.md, tutorials/irsa-sia-examples/sia_allwise_atlas.md, tutorials/irsa-sia-examples/sia_cosmos.md, tutorials/irsa-sia-examples/siav2_seip.md, tutorials/openuniversesims/openuniverse2024_roman_simulated_timedomainsurvey.md, tutorials/openuniversesims/openuniverse2024_roman_simulated_wideareasurvey.md, tutorials/parquet-catalog-demos/wise-allwise-catalog-demo.md
@troyraen has highlighted in #34 that we haven't yet done this consistency cleanup here. This is purely a cleanup of uncommented lines, so no need to run the tests.
=> DOC: making pip install cells consistent

tutorials/firefly/NEOWISE_light_curve_demo.md, tutorials/firefly/SEDs_in_Firefly.md
Other than some minor text changes:
- Removed layout setup code which was needed for slate viewer, firefly now uses triview viewer (Image, chart and table) by default which smartly handles the layout on its own
- It also shows coverage by default, so removed that cell
- Improved how TAP query is constructed (instead of defining a url quoted string, define it as regular readable string and then let the urllib parse it)
- Updated "Align and lock" cells, firefly client can do it now thanks to the tri-view (although still need to use low-level API)
- Added title to fits images being shown
@ebratton01 @joycek-ipac feel free to comment if I overlooked anything in my updates.
=> Update firefly tutorials as per the latest firefly-client API

.github/workflows/ci_tests_run_notebooks.yml, conf.py, ignore_gha_testing
fixes #51, the logic broke when I renamed the label.
=> CI: fix skip label CI skip and ignore all euclid testing for now

tutorials/cloud_access/euclid-cloud-access.md
Added a notebook to demonstrate cloud access to Euclid data (taking inspiration from Tiffany's recent notebooks)
=> Add a Euclid cloud access notebook

.binder/requirements.txt, conf.py, index.md, tutorials/cloud_access/euclid-cloud-access.md, tutorials/euclid_access/1_Euclid_intro_MER_images.md, tutorials/euclid_access/2_Euclid_intro_MER_catalog.md, tutorials/euclid_access/3_Euclid_intro_1D_spectra.md, tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
This PRs primary purpose is to add the new notebooks to the HTML pages. It will be merged just before the data release, so ideally should be independent of any improvements done to the notebooks, so we can merge those sooner.
I'll also rebase it on top of #50, so the cloud notebook is included in the rendering, too.
(Note: execution of the code is turned off here. If we want to deploy any outputs those have to be generated locally on a computer with VPN access and then pushed directly to the deploy branch)
=> Euclid rendering

tutorials/euclid_access/1_Euclid_intro_MER_images.md
The notebook 1_Euclid_intro_MER_images is displaying a pandas warning like:
```
SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
```
from a cell about 2/3 the way down that gets the `filters`. This PR adds `pd.options.mode.copy_on_write = True` to the top of the notebook to avoid this. Copy-on-write avoids unexpected modifications to the original DataFrame, is generally more performant, and will become the default in pandas 3.0.
=> Euclid: Use copy-on-write to avoid SettingWithCopyWarning

.binder/requirements.txt, .github/workflows/ci_tests_run_notebooks.yml, tox.ini
Apparently, this was never set up properly and as the latest notebooks run into issues with old versions I added minimums for all the main dependencies.
=> CI: add all the versions for the oldestjob

tutorials/euclid_access/1_Euclid_intro_MER_images.md
I've made a few changes to the first notebook, pushed them to my branch on my fork.
=> A few changes following the rehearsal

tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
A few updates to Notebook 5 based on feedback from the rehearsal.
=> Updates to euclid notebook5

test_requirements.txt, tox.ini
This should fix #79 
Note that I push the commits in sequence, the first one is expected too fail the GHA tests, and with the second one we should get a green pass. I'll ignore circleCI status here.
=> CI: fixing test status when no notebooks were collected for testing

tutorials/euclid_access/1_Euclid_intro_MER_images.md, tutorials/euclid_access/2_Euclid_intro_MER_catalog.md, tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md, tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
This is not yet exhaustive yet, but it's easier if the changes are on a branch already
=> ENH: Euclid swap pyvo for astroquery

tutorials/euclid_access/3_Euclid_intro_1D_spectra.md
This PR:
- swaps PyVO to astroquery
- uses astropy API consistently
- cleans up pandas usage as there is nothing specific it is required for
- relies on astropy Quantity support for plotting
- removes usage of BytesIO as `fits.open` is fully capable of dealing with URLs
- Cleans up the narrative a little bit to make code content and text more consistent
Please check the rendered HTMLs for an easier view.
=> Euclid: Simplify spectra notebook

tutorials/euclid_access/1_Euclid_intro_MER_images.md, tutorials/euclid_access/3_Euclid_intro_1D_spectra.md, tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md, tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
This PR sits on top of #60 and does:
- cleanup direct use of `requests` and BytesIO
- going back and forth with pandas for simple table usage and stay within astropy Table land
=> ENH: More cleanups for euclid notebooks: remove bytesIO and astropy-ify notebook 1&5

tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
We don't plot from `result_table`, so we don't strictly require it to be a `QTable`. 
So, this is a reasonable workaround while the upstream issues https://github.com/astropy/astropy/issues/17963 and the `NA` unit from the DB side are resolved.
Also, note that we see the values changed in the table during the conversions, which I still need to investigate and open relevant upstream bug reports for.
=> BUG: avoid QTable convertint int columns to float

conf.py
We do hit timeouts on the cosmodc2 notebook, and while I'm fairly certain switching to async query solved the server side timeout, we now hit the notebook execution timeout of 900s. 
So hopefully, this trick will provide a workaround, and in the meantime I'll work out how to properly use a cache between CI runs.
=> MAINT: using longer timeout to accommodate cosmodc2 async query

.circleci/config.yml, conf.py, tox.ini, tutorials/euclid_access/2_Euclid_intro_MER_catalog.md, tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md, tutorials/openuniversesims/openuniverse2024_roman_simulated_timedomainsurvey.md
Opening it as a draft as I doubt this will work at first try (and I don't really have any working examples in front of me for this).
=> CI: adding caching for notebooks

tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
Unfortunately swapping out the manual flux--mag conversions run into issues (#94 ). While doing a `result_stars["flux_y_templfit"].to(u.ABmag)` is super simple, I was running into various issues during plotting depending on how I did the magerr conversions, dealt with the masks, and if started off from a Table vs QTable.
So for now, this is the simplest swap to not converting things into a dataframe.
=> MAINT: pandas--astropy cleanup for euclid2

.gitignore, tutorials/cloud_access/euclid-cloud-access.md, tutorials/euclid_access/1_Euclid_intro_MER_images.md, tutorials/euclid_access/2_Euclid_intro_MER_catalog.md, tutorials/euclid_access/3_Euclid_intro_1D_spectra.md, tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md, tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md, tutorials/euclid_access/Euclid_ERO.md
I went with a 1 year cut-off date for the note, I think that's reasonable enough as a reminder. (we run into this issue with astroquery 0.4.10 a lot, I expect as it was released only a few days before the euclid release itself, but it came up with firefly previously).
=> DOC: adding note about having recent enough versions

.binder/requirements.txt, tox.ini
This PR removes the workaround we have for testing
=> MAINT: ray now has a py3.13 compatible release

tutorials/euclid_access/2_Euclid_intro_MER_catalog.md
In the Euclid MER catalog CMD figure, reverse the y-axis so that brighter stars are on top and zoom in to see detail a little better. The new figure looks like this (I can adjust x-and y-limits differently if wanted):
=> Euclid MER catalog CMD: Reverse y-axis and zoom in

conf.py, site_requirements.txt
~This PR is just a test for `scroll_outputs` functionality upcoming from upstream in https://github.com/executablebooks/MyST-NB/pull/683~
Fixes #69 
Test if the generated webpages have long outputs scrollable (bonus: also test dark mode style fixes that will come soon).
=> Enable nb_scroll_outputs from latest myst-nb

.github/workflows/circleci-artifacts-redirector.yml
This has to be on `main` for #119 to work. The rest of the CI changes can be done in the PR. 
I expect this to not break anything.
=> CI: adding SP proxy domain into redirect action

tutorials/cloud_access/euclid-cloud-access.md, tutorials/euclid_access/3_Euclid_intro_1D_spectra.md, tutorials/euclid_access/4_Euclid_intro_PHZ_catalog.md, tutorials/euclid_access/5_Euclid_intro_SPE_catalog.md
[IRSA-7280](https://jira.ipac.caltech.edu/browse/IRSA-7280)
Starting on Wednesday, Sept 24, TAP calls for table 'euclid.objectid_spectrafile_association_q1' will return a `'path'` column instead of a `'uri'` column and it will contain a SpectrumDM url that will return a single spectrum instead of the full MEF. This PR updates our notebooks to accommodate.
To test: Before running any notebooks, create or edit the file `~/.astropy/config/astroquery.cfg` and make sure it has at least the following lines in it. Also make sure you're connected to IPAC VPN.
```
[ipac.irsa]
tap_url = https://irsadev.ipac.caltech.edu/TAP
```
=> Update Euclid spectra calls for new SpectrumDM service

tutorials/cosmodc2/cosmoDC2_TAP_access.md
This is a semi-dummy commit with the primary aim to to test cross-fork caching (and with a hopeful benefits of solving cosmodc2 timeouts)
=> MAINT: enlarge timeout for cosmodc2 notebook

.binder/requirements.txt, index.md, toc.yml, tox.ini, tutorials/parquet-catalog-demos/irsa-hats-with-lsdb.md
Addresses [IRSA-7104](https://jira.ipac.caltech.edu/browse/IRSA-7104)
NOTE: The time performance of the notebook depends on the spatial filters defined in the beginning. I'm working with a cone at Euclid Deep Field North center, with following radius size:
cone size | notebook executed where | total execution time | comments
-- | -- | -- | --
0.5 deg | locally | 4.5-5 min | ~2 min for each of two lsdb .compute() calls (was 4+4min on Friday)
0.5 deg | CircleCI rendering | 101s = 1.68min (average of two runs) | surprisingly less! I was expecting it to be more than local. Is it because CircleCI is also on AWS or something else?
0.5 deg | Fornax SP | 75s = 1.25min | fastest of all as expected
3 deg (entire field) | Fornax SP | 192s = 3.2 min (1.5min for 1st compute()) | 6 times more cone …
=> IRSA-7104: Add "Access IRSA HATS using lsdb" notebook

.binder/requirements.txt, tutorials/parquet-catalog-demos/irsa-hats-with-lsdb.md
https://github.com/astronomy-commons/lsdb/issues/1047#issuecomment-3366994143 - the bug with universal_pathlib got resolved
=> Update lsdb version and remove universal_pathlib in requirements.txt
